use tilegraph_core::{GraphNodeExport, GraphRelationshipExport, RelationshipType};
use std::fmt::Write as FmtWrite;

/// Generates Cypher import scripts for bulk Neo4j import.
pub struct CypherGenerator;

impl CypherGenerator {
    /// Generate a Cypher MERGE statement for one node.
    pub fn node_merge(node: &GraphNodeExport) -> String {
        let mut props = serde_json::Map::new();
        props.insert("object_id".to_string(), serde_json::json!(node.object_id));
        props.insert("name".to_string(), serde_json::json!(node.name));
        props.insert("class".to_string(), serde_json::json!(node.class.to_string()));
        props.insert("status".to_string(), serde_json::json!(node.status));
        if let Some(tag) = &node.tag {
            props.insert("tag".to_string(), serde_json::json!(tag));
        }
        if let Some(tile_id) = &node.tile_id {
            props.insert("tile_id".to_string(), serde_json::json!(tile_id));
        }
        if let Some(fid) = node.feature_id {
            props.insert("feature_id".to_string(), serde_json::json!(fid));
        }
        if let Some(min) = node.aabb_min {
            props.insert("aabb_min_x".to_string(), serde_json::json!(min[0]));
            props.insert("aabb_min_y".to_string(), serde_json::json!(min[1]));
            props.insert("aabb_min_z".to_string(), serde_json::json!(min[2]));
        }
        if let Some(max) = node.aabb_max {
            props.insert("aabb_max_x".to_string(), serde_json::json!(max[0]));
            props.insert("aabb_max_y".to_string(), serde_json::json!(max[1]));
            props.insert("aabb_max_z".to_string(), serde_json::json!(max[2]));
        }
        for (k, v) in &node.properties {
            props.insert(k.clone(), v.clone());
        }
        let props_json = serde_json::Value::Object(props);
        format!(
            "MERGE (n:EngObject:{label} {{object_id: {id}}}) SET n += {props};",
            label = node.label,
            id = serde_json::json!(node.object_id),
            props = props_json,
        )
    }

    /// Generate Cypher for one relationship.
    pub fn relationship_merge(rel: &GraphRelationshipExport) -> String {
        format!(
            "MATCH (a:EngObject {{object_id: {src}}}), (b:EngObject {{object_id: {tgt}}}) \
             MERGE (a)-[:{rel_type}]->(b);",
            src = serde_json::json!(rel.source_id),
            tgt = serde_json::json!(rel.target_id),
            rel_type = rel.rel_type,
        )
    }

    /// Emit a complete import script for a batch of nodes and relationships.
    pub fn full_import_script(
        nodes: &[GraphNodeExport],
        rels: &[GraphRelationshipExport],
    ) -> String {
        let mut script = String::new();
        writeln!(script, "// TileGraphAgent — Neo4j import script").ok();
        writeln!(script, "// Generated by tilegraph-graph-export").ok();
        writeln!(script, "// Node count: {}", nodes.len()).ok();
        writeln!(script, "// Relationship count: {}", rels.len()).ok();
        writeln!(script).ok();

        for node in nodes {
            writeln!(script, "{}", Self::node_merge(node)).ok();
        }
        writeln!(script).ok();
        for rel in rels {
            writeln!(script, "{}", Self::relationship_merge(rel)).ok();
        }
        script
    }

    /// Canonical query: find all pumps connected to a line tag.
    pub fn query_pumps_connected_to_line(line_tag: &str) -> String {
        format!(
            r#"MATCH (p:Pump)-[:CONNECTED_TO]->(l:Line {{tag: {tag}}})
RETURN p.object_id AS object_id, p.tag AS tag, p.name AS name, p.status AS status,
       p.tile_id AS tile_id, p.feature_id AS feature_id;"#,
            tag = serde_json::json!(line_tag)
        )
    }

    /// Find isolation valves for a line.
    pub fn query_isolation_valves_for_line(line_tag: &str) -> String {
        format!(
            r#"MATCH (v:Valve)-[:ISOLATED_BY|PART_OF]->(l:Line {{tag: {tag}}})
WHERE v.valve_type = 'GATE' OR v.valve_type = 'BALL'
RETURN v.object_id AS object_id, v.tag AS tag, v.status AS status,
       v.tile_id AS tile_id, v.feature_id AS feature_id;"#,
            tag = serde_json::json!(line_tag)
        )
    }

    /// Find upstream objects from a given object (follow UPSTREAM_OF chain).
    pub fn query_upstream(object_id: &str, max_hops: u32) -> String {
        format!(
            r#"MATCH path = (start:EngObject {{object_id: {oid}}})-[:UPSTREAM_OF*1..{hops}]->(upstream)
RETURN upstream.object_id AS object_id, upstream.tag AS tag,
       upstream.class AS class, length(path) AS hops
ORDER BY hops;"#,
            oid = serde_json::json!(object_id),
            hops = max_hops,
        )
    }

    /// Find downstream objects.
    pub fn query_downstream(object_id: &str, max_hops: u32) -> String {
        format!(
            r#"MATCH path = (start:EngObject {{object_id: {oid}}})<-[:UPSTREAM_OF*1..{hops}]-(downstream)
RETURN downstream.object_id AS object_id, downstream.tag AS tag,
       downstream.class AS class, length(path) AS hops
ORDER BY hops;"#,
            oid = serde_json::json!(object_id),
            hops = max_hops,
        )
    }

    /// Generate maintenance context for a line shutdown.
    pub fn query_maintenance_context(line_tag: &str) -> String {
        format!(
            r#"MATCH (l:Line {{tag: {tag}}})
OPTIONAL MATCH (pump:Pump)-[:CONNECTED_TO]->(l)
OPTIONAL MATCH (valve:Valve)-[:PART_OF|ISOLATED_BY]->(l)
OPTIONAL MATCH (instr:Instrument)-[:PART_OF]->(l)
OPTIONAL MATCH (seg:PipeSegment)-[:PART_OF]->(l)
RETURN
  l.tag AS line_tag,
  l.object_id AS line_id,
  collect(DISTINCT pump.tag) AS connected_pumps,
  collect(DISTINCT valve.tag) AS isolation_valves,
  collect(DISTINCT instr.tag) AS instruments,
  count(DISTINCT seg) AS segment_count;"#,
            tag = serde_json::json!(line_tag)
        )
    }
}
